# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=80)),
                ('enterdate', models.DateTimeField(auto_now_add=True)),
                ('uniqueid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=25)),
                ('appuser', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='appuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlbook.Click'),
        ),
    ]
