# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='click',
            name='object_id',
        ),
        migrations.AddField(
            model_name='click',
            name='click_counts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
