# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-28 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='uniqueid',
            new_name='hashid',
        ),
    ]
