# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlbook', '0002_auto_20160727_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='appuser',
        ),
        migrations.AlterField(
            model_name='click',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlbook.BookMark'),
        ),
    ]
