# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('urlbook', '0003_auto_20160728_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 28, 18, 8, 9, 650567, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
